### ISSUE TITLE
登录的时候授权失败是什么原因

### ISSUE THREAD

**Issue by byronboys** [BoyaaDataCenter/seed#1]
我的账号注册成功之后，登录的时候授权失败是什么原因

![image](https://user-images.githubusercontent.com/11970344/50722102-d570ed80-1104-11e9-9f6a-3cfca176396b.png)

![image](https://user-images.githubusercontent.com/11970344/50722126-284aa500-1105-11e9-9ca3-80aaab52b18a.png)

![image](https://user-images.githubusercontent.com/11970344/50722132-3993b180-1105-11e9-9943-dc5ffbb0f6a5.png)

**Comment by Charles-Yurun** [comment]
我并没有重现您说的问题，请问您安装的是哪一个版本? 目前最新的版本是0.1.2。您可以用过pip install boyaa-seed -U 来更新到最新版本试试。

**Comment by byronboys** [comment]
已经是最新版本
![image](https://user-images.githubusercontent.com/11970344/51308139-6b4d3680-1a7c-11e9-88b7-b5ae2afd2749.png)



`python setup.py install`
执行这一步的时候报错了
![image](https://user-images.githubusercontent.com/11970344/51313238-0ef01400-1a88-11e9-8d9a-f9cf00d05fe7.png)

这个系统对环境依赖都有哪些？比如nodejs、webpack之类的，能不能提供一份环境依赖列表

**Comment by dc-boyaa** [comment]
前端编译环境依赖:
	npm 3.8.6
	node 6.0.0
	git

你那个错误的原因在于编译的时候，当前用户没有访问seed项目下文件夹的权限。
所以你可能需要切换到对应有修改相关文件夹权限的用户下。
