### ISSUE TITLE
npm run buildProd

### ISSUE THREAD

**Issue by easycmdb** [BoyaaDataCenter/seed#3]
> seed@1.0.0 buildProd /data/easyops_report/seed/seed_static
> ng build --prod --env=prod --aot

The build command requires to be run in an Angular project, but a project definition could not be found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the seed@1.0.0 buildProd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-09T15_25_11_251Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v10.15.3-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'buildProd' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'prebuildProd', 'buildProd', 'postbuildProd' ]
5 info lifecycle seed@1.0.0~prebuildProd: seed@1.0.0
6 info lifecycle seed@1.0.0~buildProd: seed@1.0.0
7 verbose lifecycle seed@1.0.0~buildProd: unsafe-perm in lifecycle true
8 verbose lifecycle seed@1.0.0~buildProd: PATH: /opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/easyops_report/seed/seed_stati
c/node_modules/.bin:/usr/local/easyops/python/tools:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/nginx/sbin/:/usr/local/mysql
/bin/:/root/bin:/root/bin
9 verbose lifecycle seed@1.0.0~buildProd: CWD: /data/easyops_report/seed/seed_static
10 silly lifecycle seed@1.0.0~buildProd: Args: [ '-c', 'ng build --prod --env=prod --aot' ]
11 silly lifecycle seed@1.0.0~buildProd: Returned: code: 1  signal: null
12 info lifecycle seed@1.0.0~buildProd: Failed to exec buildProd script
13 verbose stack Error: seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid seed@1.0.0
15 verbose cwd /data/easyops_report/seed/seed_static
16 verbose Linux 2.6.32-754.3.5.el6.x86_64
17 verbose argv "/opt/node-v10.15.3-linux-x64/bin/node" "/usr/local/bin/npm" "run" "buildProd"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
22 error Exit status 1
23 error Failed at the seed@1.0.0 buildProd script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fionsay** [comment]
> > seed@1.0.0 buildProd /data/easyops_report/seed/seed_static
> > ng build --prod --env=prod --aot
> 
> The build command requires to be run in an Angular project, but a project definition could not be found.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the seed@1.0.0 buildProd script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2019-05-09T15_25_11_251Z-debug.log
> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/opt/node-v10.15.3-linux-x64/bin/node',
> 1 verbose cli '/usr/local/bin/npm',
> 1 verbose cli 'run',
> 1 verbose cli 'buildProd' ]
> 2 info using npm@6.4.1
> 3 info using node@v10.15.3
> 4 verbose run-script [ 'prebuildProd', 'buildProd', 'postbuildProd' ]
> 5 info lifecycle seed@1.0.0~prebuildProd: seed@1.0.0 6 info lifecycle seed@1.0.0~buildProd: seed@1.0.0
> 7 verbose lifecycle seed@1.0.0~buildProd: unsafe-perm in lifecycle true 8 verbose lifecycle seed@1.0.0~buildProd: PATH: /opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/easyops_report/seed/seed_stati
> c/node_modules/.bin:/usr/local/easyops/python/tools:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/nginx/sbin/:/usr/local/mysql
> /bin/:/root/bin:/root/bin
> 9 verbose lifecycle seed@1.0.0~buildProd: CWD: /data/easyops_report/seed/seed_static 10 silly lifecycle seed@1.0.0~buildProd: Args: [ '-c', 'ng build --prod --env=prod --aot' ]
> 11 silly lifecycle seed@1.0.0~buildProd: Returned: code: 1 signal: null 12 info lifecycle seed@1.0.0~buildProd: Failed to exec buildProd script
> 13 verbose stack Error: seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
> 13 verbose stack Exit status 1
> 13 verbose stack at EventEmitter. (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 13 verbose stack at EventEmitter.emit (events.js:189:13)
> 13 verbose stack at ChildProcess. (/opt/node-v10.15.3-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack at ChildProcess.emit (events.js:189:13)
> 13 verbose stack at maybeClose (internal/child_process.js:970:16)
> 13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 14 verbose pkgid seed@1.0.0
> 15 verbose cwd /data/easyops_report/seed/seed_static
> 16 verbose Linux 2.6.32-754.3.5.el6.x86_64
> 17 verbose argv "/opt/node-v10.15.3-linux-x64/bin/node" "/usr/local/bin/npm" "run" "buildProd"
> 18 verbose node v10.15.3
> 19 verbose npm v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error seed@1.0.0 buildProd: `ng build --prod --env=prod --aot`
> 22 error Exit status 1
> 23 error Failed at the seed@1.0.0 buildProd script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

try to use later than node v10.15.3 or upgrade the dependencies.
using node v8.x.x is working.
